/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;


import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class workshop extends javax.swing.JFrame {
private final JPanel contentPane;
    /**
     * Creates new form workshop
     */
    public workshop() {
        initComponents();
        CustomCursor();
        
        setDefaultCloseOperation(workshop.DISPOSE_ON_CLOSE);
    setBounds(175, 15, 970, 700);
    contentPane = new JPanel();
    contentPane.setBackground(Color.ORANGE);
    contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
    
  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        month1 = new javax.swing.JComboBox();
        date1 = new javax.swing.JComboBox();
        year1 = new javax.swing.JComboBox();
        c = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        ENROLL = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sc = new javax.swing.JTable();
        CLEAR = new javax.swing.JButton();
        d = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        month1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        month1.setToolTipText("");
        getContentPane().add(month1);
        month1.setBounds(470, 140, 70, 20);

        date1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        date1.setBorder(null);
        date1.setOpaque(false);
        getContentPane().add(date1);
        date1.setBounds(390, 140, 70, 20);

        year1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2016", "2017", "2018", "2019" }));
        getContentPane().add(year1);
        year1.setBounds(550, 140, 70, 20);

        c.setEditable(false);
        c.setBorder(null);
        c.setOpaque(false);
        getContentPane().add(c);
        c.setBounds(680, 500, 230, 30);

        b.setEditable(false);
        b.setBorder(null);
        b.setOpaque(false);
        getContentPane().add(b);
        b.setBounds(200, 500, 230, 30);

        a.setBorder(null);
        a.setOpaque(false);
        getContentPane().add(a);
        a.setBounds(200, 410, 240, 30);

        ENROLL.setContentAreaFilled(false);
        ENROLL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENROLLActionPerformed(evt);
            }
        });
        getContentPane().add(ENROLL);
        ENROLL.setBounds(50, 600, 410, 50);

        sc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "CITY", "STATE", "Seats Left"
            }
        ));
        sc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(sc);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 190, 880, 170);

        CLEAR.setContentAreaFilled(false);
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        getContentPane().add(CLEAR);
        CLEAR.setBounds(530, 600, 410, 50);

        d.setEditable(false);
        d.setBorder(null);
        d.setOpaque(false);
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(680, 400, 230, 40);

        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(790, 130, 150, 40);

        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(810, 30, 160, 70);

        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(580, 30, 220, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshop44.png"))); // NOI18N
        jLabel8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel8FocusGained(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 970, 700);

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 30, 240, 70);

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 30, 210, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimize normal.png"))); // NOI18N
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 0, 26, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close normal.png"))); // NOI18N
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 0, 26, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minmize hover.png"))); // NOI18N
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel6MouseDragged(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 0, 30, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close hover.png"))); // NOI18N
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 0, 30, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/title bar 2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1200, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Workshop bar.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 10, 975, 130);

        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 700);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshop date pane.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 130, 350, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background 2.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 120, 970, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseDragged

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseDragged

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setState(Members_Login.ICONIFIED);       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
        jLabel7.setVisible(false);
        jLabel4.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseMoved

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved
        jLabel4.setVisible(false);
        jLabel7.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseMoved

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        main form = new main();
        form.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        workshop form = new workshop();
        form.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        gallery form = new gallery();
        form.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        Members_Login form = new Members_Login();
        form.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
jLabel4.setVisible(true);
jLabel7.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
DefaultTableModel model=(DefaultTableModel)sc.getModel();
String d1 = (String)date1.getSelectedItem();
String m = (String)month1.getSelectedItem();
String y = (String)year1.getSelectedItem();
try{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pix_craft","root","a");
Statement stmt=con.createStatement();
String query="select * from workshop where Date='"+y+"."+m+"."+d1+"';";
ResultSet rs=stmt.executeQuery(query);
while(rs.next()){
String dt = rs.getString("date");   
String st = rs.getString("state");
String ct = rs.getString("city");
String s = rs.getString("Seats_Left");
model.addRow(new Object[]{dt,ct,st,s});
}
rs.close();
stmt.close();
con.close();
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e);} 
        
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void scMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scMouseClicked
int row =sc.getSelectedRow();
{
d.setText(sc.getModel().getValueAt(row,3).toString());   
b.setText(sc.getModel().getValueAt(row,2).toString());
c.setText(sc.getModel().getValueAt(row,1).toString());
}         // TODO add your handling code here:
    }//GEN-LAST:event_scMouseClicked

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
this.dispose();
workshop form = new workshop();
form.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_CLEARActionPerformed

    private void ENROLLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENROLLActionPerformed
int s=Integer.parseInt(d.getText());
        if (s==0){
JOptionPane.showMessageDialog(null,"sorry! no seats left...");
}else
    try {Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection
        ("jdbc:mysql://localhost:3306/pix_craft", "root", "a");
        int x=Integer.parseInt(d.getText());
        int f =x-1;
        String d1 = (String)date1.getSelectedItem();
        String m = (String)month1.getSelectedItem();
        String y = (String)year1.getSelectedItem();
        String z=c.getText();
        Statement stmt = con.createStatement();
        String query1 = "UPDATE workshop set Seats_Left="+f+" WHERE CITY='"+z+"' && DATE='"+y+"-"+m+"-"+d1+"';";
        stmt.executeUpdate(query1);
        JOptionPane.showMessageDialog(null, "Registered"
                 + " Succesfully!");
        this.dispose();
        workshop form = new workshop();
        form.setVisible(true); 
stmt.close();
con.close();
        
}
    catch (Exception e){JOptionPane.showMessageDialog(null, e);}// TODO add your handling code here:
    }//GEN-LAST:event_ENROLLActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void jLabel8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel8FocusGained
    try {
        Class.forName("java.sql.Driver");
    
        Connection con = DriverManager.getConnection
        ("jdbc:mysql://localhost:3306/pix_craft", "root", "a");
        Statement stmt = con.createStatement();
        String query = "Select date from workshop;";
        ResultSet rs=stmt.executeQuery(query);
        while(rs.next()){
String dt = rs.getString("date");  
        JOptionPane.showMessageDialog(null,""+dt);}      }
    catch(Exception e){
    JOptionPane.showMessageDialog(null,e);}  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8FocusGained
    public void CustomCursor()
    {
      Toolkit toolkit = Toolkit.getDefaultToolkit();
      Image img = toolkit.getImage("cursor.png");
      Point point = new Point(0,0);
      Cursor Cursor = toolkit.createCustomCursor(img, point, "cursor");
      setCursor(Cursor);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new workshop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton ENROLL;
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JComboBox date1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox month1;
    private javax.swing.JTable sc;
    private javax.swing.JComboBox year1;
    // End of variables declaration//GEN-END:variables
}
